theme: jekyll-theme-minimal
title: [Página do Curso de Derivação Racional por Fatores]
description: [Um curso que visa capacitar os avaliadores a derivar e utilizar racionalmente fatores de homogeneização]