theme: jekyll-theme-minimal
title: [Derivação Racional de Fatores]
description: [Capacitação de avaliadores na derivação e utilização racional de fatores de homogeneização]
logo: /assets/img/logo.png
description: Um curso Valoristica